version: '3.7'
services:
  postgresql:
    image: postgres:14-alpine
    ports:
      - '22:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=natasha
      - POSTGRES_PASSWORD=qwerty123